version: "3.8"
services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "birthday-bot-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"